breadandcake/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.products, name='products'),
    path('product/<int:product_id>/', views.productDetails, name='productDetails'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]

easybakers/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('breadandcake.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

breadandcake/models.py
from django.db import models
from django.contrib.auth.models import User

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    contact = models.CharField(max_length=15, null=True)
    location = models.CharField(max_length=15, null=True)
    email = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.FloatField()
    image = models.ImageField(null=True, blank=True)
    description = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

class Offer(models.Model):
    price= models.CharField(max_length=200, null=True)
    title= models.CharField(max_length=200, null=True)
    description= models.CharField(max_length=200, null=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

class Testimonial(models.Model):
    message= models.CharField(max_length=200, null=True)
    image = models.ImageField(null=True, blank=True)
    name= models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

class Contact(models.Model):
    name = models.CharField(max_length=100, null=True)
    phone = models.CharField(max_length=15, null=True)
    email = models.CharField(max_length=100, null=True)
    subject = models.CharField(max_length=100, null=True)
    message = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.name

breadandcake/forms.py
from django import forms
from django.core.validators import EmailValidator

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, label='Name')
    phone = forms.CharField(max_length=15, label='Phone')
    email = forms.EmailField(validators=[EmailValidator()], label='Email')
    subject = forms.CharField(max_length=100, label='Subject')
    message = forms.CharField(widget=forms.Textarea, label='Message')

breadandcake/views.py
from django.template import loader
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from . forms import ContactForm

def home(request):
  products = Product.objects.all()[:8]
  context = {'products':products}
  return render(request, 'home/index.html', context)

def products(request):
  products = Product.objects.all()
  offer = Offer.objects.all()[:1]
  context = {'products':products}
  return render(request, 'home/products.html', context)

def productDetails(request, product_id):
  product = get_object_or_404(Product, pk=product_id)
  products = Product.objects.all()[:4]
  context = {'products':products, 'product': product}
  return render(request, 'home/product_details.html', context)

def about(request):
  return render(request, 'home/about.html')

from django.shortcuts import render, redirect
from .forms import ContactForm
from .models import Contact  # Assuming Contact is defined in your models

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            new_contact = Contact(
                name=form.cleaned_data['name'],
                phone=form.cleaned_data['phone'],
                email=form.cleaned_data['email'],
                subject=form.cleaned_data['subject'],
                message=form.cleaned_data['message']
            )
            new_contact.save()
            return redirect('contact')
    else:
        form = ContactForm()

    return render(request, 'home/contact.html', {'form': form})

breadandcake/templates/home/about.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF -8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title> About | Easy Bakers | The Bread and Cake Shop</title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link href="https://fonts.googleapis.com/css2?
        family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    </head>
    <body>

        <!-- Header -->
        <div class="header">
            <div class="navbar">
                <div class="logo" style="display: flex; justify-content: center; align-items: center;">
                    <img src="/images/logo.png" width="40px" height="40px" style="margin: 0 2px;">
                    <h2 style="color: #555;">Easy Bakers and Confectioners LTD</h2>
                </div>
                <nav>
                    <ul id="MenuItems">
                        <li><a href="/">Home</a></li>
                        <li><a href="/products">Products</a></li>
                        <li><a href="/about">About</a></li>
                        <li><a href="/contact">Contact</a></li>
                    </ul>
                </nav>
                <i class="fa-solid fa-bars" onclick="menutoggle()"></i>
            </div>
        </div>

        <div class="heading">
            <h1>About Us</h1>
            <p style="font-size: 16px;">
                Welcome to Easy Bakers and Confectioners Ltd, where the scent of freshly baked goods fills the air and your sweetest dreams are brought to life.
            </p>
        </div>
        <div class="about-container small-container">
            <div class="about">
                <div class="about-image">
                    <img src="/images/File_00244.jpg">
                </div>
                <div class="about-content">
                    <h2>Our History</h2>
                    <p style="font-size: 16px;">
                        Our story began in 2001, with a passion for baking. Our founder, Mr. Amin with a pinch of love and a dash of creativity brought those classic recipes to life in our very own bakery.
                        <br>
                        Today, we're proud to be a part of this vibrant community, serving up freshly baked bread, pastries, cakes, and treats that bring people together. Our bakery is a place where tradition meets innovation, where every bite is a delight for the senses, and where every customer is treated like family.
                        <br>
                        We believe that baking is an art form, and we're dedicated to crafting every item with love and care. From classic favorites to new creations, our menu is designed to inspire and delight. Whether you're a longtime local or just visiting, we invite you to come taste the love and warmth that goes into every single item we bake.
                        <br>
                        So, come on in, and let's share a slice of joy together!"
                    </p>
                    <div class="social-links">
                        <a href=""><i class="fab fa-instagram"></i></a>
                        <a href=""><i class="fab fa-x"></i></a>
                        <a href=""><i class="fab fa-tiktok"></i></a>
                        <a href=""><i class="fab fa-facebook"></i></a>
                    </div>
                </div>
            </div>
        </div>


        <div class="about-container small-container">
            <div class="about">
                <div class="about-content">
                    <h2>A letter from Bread and Cake Family</h2>
                    <p style="font-size: 16px;">
                        We are thrilled to welcome you to our community of Bread and Cake and we are greatful to each and everyone who has supported
                        us in this journey since 2001.
                        <br>
                        After years of honing our craft and perfecting our recipes, we finally took a leap and opened a website so that we can be able to reach each and
                        everyone around the globe.
                        <br>
                        Our bakery and shop outlets are more than just a place to grab a bite. They are gathering spots, hub for connection and community and
                        we've been humbled by the out-pouring support from our customers, who have become like family to us.
                        <br>
                        So we thank you for joining us on this journey, whether you're a long time customer, local or just visiting, we can't wait to welcome you into
                        our family.
                    </p>
                    <br>
                    <em>Happiness is only a Queen Cake Away</em>
                    <div class="social-links">
                        <a href=""><i class="fab fa-instagram"></i></a>
                        <a href=""><i class="fab fa-x"></i></a>
                        <a href=""><i class="fab fa-tiktok"></i></a>
                        <a href=""><i class="fab fa-facebook"></i></a>
                    </div>
                    <a href="/contact" class="btn">Contact Us</a>
                </div>
                <div class="about-image">
                    <img src="/images/File_00230.jpg" style="background-color: #ece2e2;">
                </div>
            </div>
        </div>

       
        <div class="about-container small-container">
            <h2 class="title">Our Outlet Menus</h2>
            <div class="about">
                <div class="about-image">
                    <img src="/images/menu-1.png" style="width: 100%; height: 550px;">
                </div>
                <div class="about-content">
                    <h2>Kampala Road Outlet</h2>
                    <p style="font-size: 16px;">
                        <strong>Grap refreshments from our Kampala-Road Outlet. See Menu!</strong>
                        <br>
                        From soft drinks to Coffee. We offer the best refereshments in the heart of the city.
                        <br>
                        Enjoy snacks, light and big meals, as well as biverages from our Kampala-Road Outlet.
                        <br>
                    </p>
                    <br>
                    <em>Dine with us. The Bread and Cake Shop!</em>
                    <div class="social-links">
                        <a href=""><i class="fab fa-instagram"></i></a>
                        <a href=""><i class="fab fa-x"></i></a>
                        <a href=""><i class="fab fa-tiktok"></i></a>
                        <a href=""><i class="fab fa-facebook"></i></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="about-container small-container">
            <div class="about">
                <div class="about-content">
                    <h2>De winton Road Outlet</h2>
                    <p style="font-size: 16px;">
                        <strong>Grap refreshments from our De winton-Road Outlet. See Menu!</strong>
                        <br>
                        From soft drinks to Coffee. We offer the best refereshments in the heart of the city.
                        <br>
                        Enjoy snacks, light and big meals, as well as biverages from our De winton-Road Outlet Outlet.
                        <br>
                    </p>
                    <br>
                    <em>Dine with us. The Bread and Cake Shop!</em>
                    <div class="social-links">
                        <a href=""><i class="fab fa-instagram"></i></a>
                        <a href=""><i class="fab fa-x"></i></a>
                        <a href=""><i class="fab fa-tiktok"></i></a>
                        <a href=""><i class="fab fa-facebook"></i></a>
                    </div>
                </div>
                <div class="about-image">
                    <img src="/images/menu-2.png" style="width: 100%; height: 550px;">
                </div>
            </div>
        </div>

        
       
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="footer-col-1">
                        <h3>Easy Bakers and Confectioners ltd</h3>
                        <div class="app-logo">
                            <img src="/images/logo.png">
                        </div>
                    </div>
                    <div class="footer-col-2">
                        <img src="/images/IMG_0042.png">
                        <p style="color: #c8c8c8;">
                            Take your taste buds for a spin. Freshly baked every morning.
                        </p>
                    </div>
                    <div class="footer-col-3">
                        <h3>Contacts</h3>
                                                <ul>
                            <div style="display: flex; justify-content: center;">
                                <i class="fas fa-map-marker-alt" style="margin-right: 5px;"></i>
                                <p style="color: #c8c8c8;">Kampala, old port-bell road</p>
                            </div>
                            <div style="display: flex; justify-content: center;">
                                <i class="fas fa-phone" style="margin-right: 5px;"></i>
                                <p style="color: #c8c8c8;">+256759443880</p>
                            </div>
                            <div style="display: flex; justify-content: center;">
                                <i class="fas fa-phone" style="margin-right: 5px;"></i>
                                <p style="color: #c8c8c8;">+256772505622</p>
                            </div>
                            <div style="display: flex; justify-content: center;">
                                <i class="fas fa-envelope" style="margin-right: 5px;"></i>
                                <p style="color: #c8c8c8;">easybakers222@gmail.com</p>
                            </div>
                        </ul>
                    </div>
                    <div class="footer-col-4">
                        <h3>Follow us on</h3>
                        <ul>
                            <a href=""><i class="fab fa-instagram" style="color: #c8c8c8;"></i></a>
                            <a href=""><i class="fab fa-x" style="color: #c8c8c8;"></i></a>
                            <a href=""><i class="fab fa-tiktok" style="color: #c8c8c8;"></i></a>
                            <a href=""><i class="fab fa-facebook" style="color: #c8c8c8;"></i></a>
                        </ul>
                    </div>
                </div>
                <hr>

                <p class="copyright">@Vellfar 2024</p>
            </div>
        </div>
        <script src="https://kit.fontawesome.com/f8a9fd1092.js" crossorigin="anonymous"></script>

        <script>
            var MenuItems = document.getElementById("MenuItems");

            MenuItems.style.maxHeight = "0px";

            function menutoggle(){
                if(MenuItems.style.maxHeight == "0px")
                    {
                        MenuItems.style.maxHeight = "200px";
                    }
                else
                    {
                        MenuItems.style.maxHeight = "0px";
                    }
            }
        </script>
    </body>
</html>
{% endblock content %}

breadandcake/templates/home/contact.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF -8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title> Contact | Easy Bakers | The Bread and Cake Shop</title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link href="https://fonts.googleapis.com/css2?
        family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    </head>
    <body>

        <!-- Header -->
        <div class="header">
            <div class="navbar">
                <div class="logo" style="display: flex; justify-content: center; align-items: center;">
                    <img src="/images/logo.png" width="40px" height="40px" style="margin: 0 2px;">
                    <h2 style="color: #555;">Easy Bakers and Confectioners LTD</h2>
                </div>
                <nav>
                    <ul id="MenuItems">
                        <li><a href="/">Home</a></li>
                        <li><a href="/products">Products</a></li>
                        <li><a href="/about">About</a></li>
                        <li><a href="/contact">Contact</a></li>
                    </ul>
                </nav>
                <i class="fa-solid fa-bars" onclick="menutoggle()"></i>
            </div>
        </div>

        <div class="contact-container">
            <h1>Connect with us!</h1>
            <p>
                We would love to attend to your orders and respond to your inquiries.
                Feel free to get in touch with us.
            </p>
            <div class="contact-box">
                <div class="contact-left">
                    <h3>Send your order or request!</h3>
                    <form id="uploadForm" action="{% url 'contact' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="input-row">
                            <div class="input-group">
                                <label for="id_name">Name</label>
                                <input type="text" name="name" id="id_name" required>
                            </div>
                            <div class="input-group">
                                <label for="id_phone">Phone No</label>
                                <input type="text" name="phone" id="id_phone" required>
                            </div>
                        </div>
                        <div class="input-row">
                            <div class="input-group">
                                <label for="id_email">Email</label>
                                <input type="email" name="email" id="id_email" required>
                            </div>
                            <div class="input-group">
                                <label for="id_subject">Subject</label>
                                <input type="text" name="subject" id="id_subject" required>
                            </div>
                        </div>
                    
                        <label for="id_message" style="display: block; margin-bottom: 5px; font-weight: bold; color: #333;">Message</label>
                        <textarea name="message" id="id_message" rows="7" placeholder="Your Message" required></textarea>
                    
                        <button type="submit" class="btn" style="width: 200px; border: none; outline: none; box-shadow: 0px 5px 15px 0px rgba(0, 0, 0, 0.1);">Send</button>
                    </form>
                    
                </div>
                <div class="contact-right">
                    <h3>Reach Us!</h3>

                    <table>
                        <tr>
                            <td><a href="mailto:easybakers222@gmail.com" style="color: #fff;"><i class="fas fa-envelope"></i></a></td>
                            <td><a href="mailto:easybakers222@gmail.com" style="color: #fff;">easybakers222@gmail.com</a></td>
                        </tr>
                        <tr>
                            <td><a href="tel:+256772505622" style="color: #fff;"><i class="fas fa-phone"></i></a></td>
                            <td><a href="tel:+256772505622" style="color: #fff;">+256772505622</a></td>
                        </tr>
                        <tr>
                            <td><a href="tel:+256759443880" style="color: #fff;"><i class="fas fa-phone"></i></a></td>
                            <td><a href="tel:+256759443880" style="color: #fff;">+256759443880</a></td>
                        </tr>
                        <tr>
                            <td><a href="tel:+256756122224" style="color: #fff;"><i class="fas fa-phone"></i></a></td>
                            <td><a href="tel:+256756122224" style="color: #fff;">+256756122224</a></td>
                        </tr>                         
                        <tr>
                            <td><i class="fas fa-map-marker-alt"></i></td>
                            <td>kampala, Old port bell road</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
       
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="footer-col-1">
                        <h3>Easy Bakers and Confectioners ltd</h3>
                        <div class="app-logo">
                            <img src="/images/logo.png">
                        </div>
                    </div>
                    <div class="footer-col-2">
                        <img src="/images/IMG_0042.png">
                        <p style="color: #c8c8c8;">
                            Take your taste buds for a spin. Freshly baked every morning.
                        </p>
                    </div>
                    <div class="footer-col-3">
                        <h3>Contacts</h3>
                        <ul>
                            <div style="display: flex; justify-content: center;">
                                <i class="fas fa-map-marker-alt" style="margin-right: 5px;"></i>
                                <p style="color: #c8c8c8;">Kampala, old port-bell road</p>
                            </div>
                            <div style="display: flex; justify-content: center;">
                                <i class="fas fa-phone" style="margin-right: 5px;"></i>
                                <p style="color: #c8c8c8;">+256759443880</p>
                            </div>
                            <div style="display: flex; justify-content: center;">
                                <i class="fas fa-phone" style="margin-right: 5px;"></i>
                                <p style="color: #c8c8c8;">+256772505622</p>
                            </div>
                            <div style="display: flex; justify-content: center;">
                                <i class="fas fa-envelope" style="margin-right: 5px;"></i>
                                <p style="color: #c8c8c8;">easybakers222@gmail.com</p>
                            </div>
                        </ul>
                    </div>
                    <div class="footer-col-4">
                        <h3>Follow us on</h3>
                        <ul>
                            <a href=""><i class="fab fa-instagram" style="color: #c8c8c8;"></i></a>
                            <a href=""><i class="fab fa-x" style="color: #c8c8c8;"></i></a>
                            <a href=""><i class="fab fa-tiktok" style="color: #c8c8c8;"></i></a>
                            <a href=""><i class="fab fa-facebook" style="color: #c8c8c8;"></i></a>
                        </ul>
                    </div>
                </div>
                <hr>

                <p class="copyright">@Vellfar 2024</p>
            </div>
        </div>
        <script src="https://kit.fontawesome.com/f8a9fd1092.js" crossorigin="anonymous"></script>

        <script>
            var MenuItems = document.getElementById("MenuItems");

            MenuItems.style.maxHeight = "0px";

            function menutoggle(){
                if(MenuItems.style.maxHeight == "0px")
                    {
                        MenuItems.style.maxHeight = "200px";
                    }
                else
                    {
                        MenuItems.style.maxHeight = "0px";
                    }
            }
        </script>
    </body>
</html>
{% endblock content %}

breadandcake/templates/home/product_details.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF -8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Product</title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link href="https://fonts.googleapis.com/css2?
        family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    </head>
    <body>

        <!-- Header -->
        <div class="header">
            <div class="navbar">
                <div class="logo" style="display: flex; justify-content: center; align-items: center;">
                    <img src="/images/logo.png" width="40px" height="40px" style="margin: 0 2px;">
                    <h2 style="color: #555;">Easy Bakers and Confectioners LTD</h2>
                </div>
                <nav>
                    <ul id="MenuItems">
                        <li><a href="/">Home</a></li>
                        <li><a href="/products">Products</a></li>
                        <li><a href="/about">About</a></li>
                        <li><a href="/contact">Contact</a></li>
                    </ul>
                </nav>
                <i class="fa-solid fa-bars" onclick="menutoggle()"></i>
            </div>
        </div>

        <!--Single product details-->
        <div class="small-container single-product" style="top: 16px;">
            <!-- templates/home/product_details.html -->
            <div class="row">
                <div class="col-2">
                    <img src="{{ product.imageURL }}" style="padding: 10px;">
                </div>
                <div class="col-2">
                    <p>Easy Bakers and Confectioners Ltd</p>
                    <h1>{{ product.name }}</h1>
                    <h4>shs {{ product.price }}</h4>
                    <a href="/contact" class="product-btn">Contact to order</a>
                    <h3>Product Details:</h3>
                    <br>
                    <p>{{ product.description }}</p>
                </div>
            </div>

        </div>
        <!--title-->
        <div class="small-container">
            <div class="row">
                <h2 style="margin-bottom: 20px;">Featured</h2>
            </div>
        </div>
        <!--products -->
        <div class="small-container" style="margin-bottom: 40px;">
            <div class="row">
                {% for product in products %}
                <div class="col-4">
                    <img src="{{product.imageURL}}">
                    <h4>{{product.name}}</h4>
                    
                    <p>Shs {{product.price}}</p>
                    <a href="{% url 'productDetails' product.id %}" class="product-btn">View</a>
                </div>
                {% endfor %}
            </div>
        </div>
       
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="footer-col-1">
                        <h3>Easy Bakers and Confectioners ltd</h3>
                        <div class="app-logo">
                            <img src="/images/logo.png">
                        </div>
                    </div>
                    <div class="footer-col-2">
                        <img src="/images/IMG_0042.png">
                        <p style="color: #c8c8c8;">
                            Take your taste buds for a spin. Freshly baked every morning.
                        </p>
                    </div>
                    <div class="footer-col-3">
                        <h3>Contacts</h3>
                        <ul>
                            <div style="display: flex; justify-content: center;">
                                <i class="fas fa-map-marker-alt" style="margin-right: 5px;"></i>
                                <p style="color: #c8c8c8;">Kampala, old port-bell road</p>
                            </div>
                            <div style="display: flex; justify-content: center;">
                                <i class="fas fa-phone" style="margin-right: 5px;"></i>
                                <p style="color: #c8c8c8;">+256759443880</p>
                            </div>
                            <div style="display: flex; justify-content: center;">
                                <i class="fas fa-phone" style="margin-right: 5px;"></i>
                                <p style="color: #c8c8c8;">+256772505622</p>
                            </div>
                            <div style="display: flex; justify-content: center;">
                                <i class="fas fa-envelope" style="margin-right: 5px;"></i>
                                <p style="color: #c8c8c8;">easybakers222@gmail.com</p>
                            </div>
                        </ul>
                    </div>
                    <div class="footer-col-4">
                        <h3>Follow us on</h3>
                        <ul>
                            <a href=""><i class="fab fa-instagram" style="color: #c8c8c8;"></i></a>
                            <a href=""><i class="fab fa-x" style="color: #c8c8c8;"></i></a>
                            <a href=""><i class="fab fa-tiktok" style="color: #c8c8c8;"></i></a>
                            <a href=""><i class="fab fa-facebook" style="color: #c8c8c8;"></i></a>
                        </ul>
                    </div>
                </div>
                <hr>

                <p class="copyright">@Vellfar 2024</p>
            </div>
        </div>
        <script src="https://kit.fontawesome.com/f8a9fd1092.js" crossorigin="anonymous"></script>

        <script>
            var MenuItems = document.getElementById("MenuItems");

            MenuItems.style.maxHeight = "0px";

            function menutoggle(){
                if(MenuItems.style.maxHeight == "0px")
                    {
                        MenuItems.style.maxHeight = "200px";
                    }
                else
                    {
                        MenuItems.style.maxHeight = "0px";
                    }
            }
        </script>
    </body>
</html>
{% endblock content %}